name: SORTABLE CI

on:
  push:
    branches:
      - reducer_branch

defaults:
  run:
    working-directory: ./

jobs:
  unit-test: # realizando pruebas unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
